# Applied Data Science Capstone -- Week 3
## Segmenting and Clustering Neighborhoods in Toronto -- Part 1

First, import the data table into a dataframe:

In [1]:
import pandas as pd

data1 = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]
data1.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights
7      M6A        North York    Lawrence Manor
8      M7A      Queen's Park      Not assigned
9      M8A      Not assigned      Not assigned

Remove records where a Borough is not assigned to a Postcode:

In [2]:
data1.drop(index=data1.loc[data1['Borough']=='Not assigned'].index, inplace=True)  # remove postcodes not assigned
data1.reset_index(inplace=True)  # reindex remaining entries
data1.drop(columns='index', inplace=True)  # remove extra index column
data1.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights
5      M6A        North York    Lawrence Manor
6      M7A      Queen's Park      Not assigned
7      M9A         Etobicoke  Islington Avenue
8      M1B       Scarborough             Rouge
9      M1B       Scarborough           Malvern

If Neighborhood is not assigned, rename to Borough name:

In [3]:
renamelist=data1.loc[data1['Neighbourhood']=='Not assigned'].index
data1.iloc[renamelist,2]=data1.iloc[renamelist,1]  # for each neighborhood not assigned, rename to Borough
data1.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights
5      M6A        North York    Lawrence Manor
6      M7A      Queen's Park      Queen's Park
7      M9A         Etobicoke  Islington Avenue
8      M1B       Scarborough             Rouge
9      M1B       Scarborough           Malvern

If a Postcode contains multiple neighborhoods, combine them into the first postcode entry and then remove duplicate postcode entries

In [4]:
data1['Dupes']=data1.duplicated(subset='Postcode') #identify duplicate Postcodes

for i in data1.index:
    if not data1.iloc[i,3]:  # if Dupes=False, advance, keeping track if it is first duplicate entry
        k=i
    else:
        data1.iloc[k,2]=data1.iloc[k,2]+', '+data1.iloc[i,2]  #if Dupes=True, append neighborhood indo first duplicate entry
    
data1.drop(index=data1.loc[data1['Dupes']].index, inplace=True)  #remove the duplicate entries and reindex
data1.reset_index(inplace=True)
data1.drop(columns=['index','Dupes'], inplace=True)  #remove extra columns
data1.head(20)

,Postcode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Harbourfront, Regent Park"
3,M6A,North York,"Lawrence Heights, Lawrence Manor"
4,M7A,Queen's Park,Queen's Park
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,"Rouge, Malvern"
7,M3B,North York,Don Mills North
8,M4B,East York,"Woodbine Gardens, Parkview Hill"
9,M5B,Downtown Toronto,"Ryerson, Garden District"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ..."
12,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
13,M3C,North York,"Flemingdon Park, Don Mills South"
14,M4C,East York,Woodbine Heights
15,M5C,Downtown Toronto,St. James Town
16,M6C,York,Humewood-Cedarvale
17,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol..."
18,M1E,Scarborough,"Guildwood, Morningside, West Hill"
19,M4E,East Toronto,The Beaches

Print number of rows in dataframe

In [5]:
print("Number of rows in Postcode dataframe:  " + str(data1.shape[0]))

Number of rows in Postcode dataframe:  103